import Head from 'next/head'
import Header from '@/components/Header'
import Sidebar from '@/components/Sidebar';
import TopCards from '@/components/TopCards';
import BarChart from '@/components/BarChart';
import RecentOrders from '@/components/RecentOrders';

export default function Home() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex'>
        <main className='bg-gray-100 min-h-screen w-full'>
          <Header />
          <TopCards />
          <div className='flex md:flex-row flex-col p-4 gap-4'>
            <BarChart />
            <RecentOrders />
          </div>
        </main>
      </div>
    </>
  )
}
